# Generated by Django 3.1.2 on 2020-10-12 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=250)),
                ('unit_code', models.CharField(max_length=10, unique=True)),
                ('year', models.IntegerField()),
                ('semister', models.IntegerField()),
                ('unit_lecturer', models.ForeignKey(limit_choices_to={'staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.IntegerField()),
                ('exam', models.IntegerField()),
                ('total', models.IntegerField()),
                ('grade', models.CharField(max_length=1)),
                ('remark', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.unit')),
            ],
        ),
    ]
